server:
  port: 80
  servlet:
    session:
      timeout: 30m # 默认30m 不能小于1分钟
      cookie:
        name: JSESSIONID # 统一指定浏览器中Cookie保存的SessionID名称

spring:
  thymeleaf:
    cache: false # 关闭thymeleaf缓存
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/spring_security?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: xxx
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #最大活跃数
      maxActive: 20
      #初始化数量
      initialSize: 1
      #最大连接等待超时时间
      maxWait: 60000
      #打开PSCache，并且指定每个连接PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      #通过connectionProperties属性来打开mergeSql功能；慢SQL记录
      #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 1 from dual
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      #配置监控统计拦截的filters，去掉后监控界面sql将无法统计,'wall'用于防火墙
      filters: stat, wall
      stat-view-servlet:
        login-password: pywang
        login-username: pywang
  session:
    store-type: redis # 使用redis存储session信息
  redis:
    port: 6379 # 本地环境可以不配置
    host: xxxx # 本地环境可以不配置
  mvc:
    hiddenmethod:
      filter:
        enabled: true # 开启对put和delete请求方式的支持

# 资源权限分配配置
mengxuegu:
  security:
    authentication:
      loginPage: /login/page  # 登录页面
      loginProcessingUrl: /login/form  #登录请求rul
      usernameParameter: name  # 表单用户名参数名
      passwordParameter: pwd  # 表单密码参数名
      staticPaths:  # 静态资源路径
        - /dist/**
        - /modules/**
        - /plugins/**
      loginType: REDIRECT # 认证之后相应的类型
      permitUrls: # 不需验证，放行URL
        - /login/page
        - /code/image
        - /mobile/page
        - /code/mobile
      tokenValiditySeconds: 604800 # 记住我有效市场，单位秒

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    # 逻辑删除配置
    db-config:
      # 删除前
      logic-not-delete-value: 1
      # 删除后
      logic-delete-value: 0
  type-aliases-package: com.mengxuegu.web.entites

# sql打印
logging:
  level:
    com.mengxuegu.web.mapper: debug
